name : workflow-pull-request

on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Validame el repostorio
      uses: actions/checkout@v2
    
    - name: Validar ython
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'
        architecture: 'x64'
    
    - name: Instalar librer√≠as
      run: pip3 install -r requirements.txt

    - name: Correr los Tests
      run: python3 -m unittest -v